### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by not-matthias** [htl-perg-2019-20-5ahif/contact-list-exercise-not-matthias#1]
@rstropek

I implemented all the requests, but couldn't publish it to an Azure App Service, even though I'm already signed in.

**Comment by rstropek** [comment]
Looks good, thank you. Here are some tips for further improvement:

* Why is `Person.Id` a nullable `int`? If it is required, it shouldn't be nullable, should it?
* Instead of `Where(...).Count()` you could use [`Any`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.any?view=netcore-3.0#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Boolean__)
* Can you ever reach the line `return BadRequest("Invalid input(e.g.required field missing or empty)")`? If so, how would the request look like?
* According to the spec, the name filter for the `findPersonByName` operation should be in the query, not in the path -> does not fulfill requirements 100%
* According to the spec, `delete` should return `not found` if the specified ID could not be found. Don't your return `BadRequest` in that case?

Greetings,
Rainer Stropek

**Comment by not-matthias** [comment]
I updated the code again and implemented all the improvements. 

> Can you ever reach the line return BadRequest("Invalid input(e.g.required field missing or empty)")?

I changed it, that it will be reached, whenever you try to pass an empty email or invalid id. Originally, I meant to execute this line, if you try to add a new person with an already existing id, but forgot to change the error message.

--- 

I also tried to publish it, but I couldn't get it to work,  because Azure Web Services doesn't work with .NET Core 3.0.0.

(https://contact-list20190930084538.azurewebsites.net/)

**Comment by rstropek** [comment]
The extra point is yours.

@Core 3 on Azure: There is a *site extension* for that ([docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/azure-apps/?view=aspnetcore-3.0&tabs=visual-studio#deploy-aspnet-core-30-to-azure-app-service))

Greetings,
Rainer Stropek.
